name: guia13alumnos

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-notesdb}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devops123}
    volumes: [postgres-data:/var/lib/postgresql/data]
    networks: [app]
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME:-notesdb}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-devops123}
      APP_USER: ${APP_USER:-admin}
      APP_PASSWORD: ${APP_PASSWORD:-devops123}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-cambiame}
    depends_on:
      db: {condition: service_healthy}
    networks: [app]
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports: ["127.0.0.1:${FRONTEND_PORT:-8080}:80"]
    depends_on:
      backend: {condition: service_healthy}
    networks: [app]
networks: {app: {}}
volumes: {postgres-data: {}}
